
COUNTRIES = [
    ('Afghanistan','Afghanistan'),
    ('Albania','Albania'),
    ('Algeria','Algeria'),
    ('Andorra','Andorra'),
    ('Angola','Angola'),
    ('Antigua and Barbuda','Antigua and Barbuda'),
    ('Argentina','Argentina'),
    ('Armenia','Armenia'),
    ('Australia','Australia'),
    ('Austria','Austria'),
    ('Azerbaijan','Azerbaijan'),
    ('Bahamas (the)','Bahamas (the)'),
    ('Bahrain','Bahrain'),
    ('Bangladesh','Bangladesh'),
    ('Barbados','Barbados'),
    ('Belarus','Belarus'),
    ('Belgium','Belgium'),
    ('Belize','Belize'),
    ('Benin','Benin'),
    ('Bhutan','Bhutan'),
    ('Bolivia (Plurinational State of)','Bolivia (Plurinational State of)'),
    ('Bosnia and Herzegovina','Bosnia and Herzegovina'),
    ('Botswana','Botswana'),
    ('Brazil','Brazil'),
    ('Brunei Darussalam','Brunei Darussalam'),
    ('Bulgaria','Bulgaria'),
    ('Burkina Faso','Burkina Faso'),
    ('Burundi','Burundi'),
    ('Cabo Verde','Cabo Verde'),
    ('Cambodia','Cambodia'),
    ('Cameroon','Cameroon'),
    ('Canada','Canada'),
    ('Central African Republic (the)','Central African Republic (the)'),
    ('Chad','Chad'),
    ('Chile','Chile'),
    ('China','China'),
    ('Colombia','Colombia'),
    ('Comoros (the)','Comoros (the)'),
    ('Congo (the)','Congo (the)'),
    ('Costa Rica','Costa Rica'),
    ("Côte d'Ivoire","Côte d'Ivoire"),
    ('Croatia','Croatia'),
    ('Cuba','Cuba'),
    ('Cyprus','Cyprus'),
    ('Czechia','Czechia'),
    ("Democratic People's Republic of Korea (the)","Democratic People's Republic of Korea (the)"),
    ('Democratic Republic of the Congo (the)','Democratic Republic of the Congo (the)'),
    ('Denmark','Denmark'),
    ('Djibouti','Djibouti'),
    ('Dominica','Dominica'),
    ('Dominican Republic (the)','Dominican Republic (the)'),
    ('Ecuador','Ecuador'),
    ('Egypt','Egypt'),
    ('El Salvador','El Salvador'),
    ('Equatorial Guinea','Equatorial Guinea'),
    ('Eritrea','Eritrea'),
    ('Estonia','Estonia'),
    ('Eswatini','Eswatini'),
    ('Ethiopia','Ethiopia'),
    ('Fiji','Fiji'),
    ('Finland','Finland'),
    ('France','France'),
    ('Gabon','Gabon'),
    ('Gambia (the)','Gambia (the'),
    ('Georgia','Georgia'),
    ('Germany','Germany'),
    ('Ghana','Ghana'),
    ('Greece','Greece'),
    ('Grenada','Grenada'),
    ('Guatemala','Guatemala'),
    ('Guinea','Guinea'),
    ('Guinea-Bissau','Guinea-Bissau'),
    ('Guyana','Guyana'),
    ('Haiti','Haiti'),
    ('Honduras','Honduras'),
    ('Hungary','Hungary'),
    ('Iceland','Iceland'),
    ('India','India'),
    ('Indonesia','Indonesia'),
    ('Iran (Islamic Republic of)','Iran (Islamic Republic of)'),
    ('Iraq','Iraq'),
    ('Ireland','Ireland'),
    ('Israel','Israel'),
    ('Italy','Italy'),
    ('Jamaica','Jamaica'),
    ('Japan','Japan'),
    ('Jordan','Jordan'),
    ('Kazakhstan','Kazakhstan'),
    ('Kenya','Kenya'),
    ('Kiribati','Kiribati'),
    ('Kuwait','Kuwait'),
    ('Kyrgyzstan','Kyrgyzstan'),
    ("Lao People's Democratic Republic (the)","Lao People's Democratic Republic (the"),
    ('Latvia','Latvia'),
    ('Lebanon','Lebanon'),
    ('Lesotho','Lesotho'),
    ('Liberia','Liberia'),
    ('Libya','Libya'),
    ('Liechtenstein','Liechtenstein'),
    ('Lithuania','Lithuania'),
    ('Luxembourg','Luxembourg'),
    ('Madagascar','Madagascar'),
    ('Malawi','Malawi'),
    ('Malaysia','Malaysia'),
    ('Maldives','Maldives'),
    ('Mali','Mali'),
    ('Malta','Malta'),
    ('Marshall Islands (the)','Marshall Islands (the)'),
    ('Mauritania','Mauritania'),
    ('Mauritius','Mauritius'),
    ('Mexico','Mexico'),
    ('Micronesia (Federated States of)','Micronesia (Federated States of)'),
    ('Monaco','Monaco'),
    ('Mongolia','Mongolia'),
    ('Montenegro','Montenegro'),
    ('Morocco','Morocco'),
    ('Mozambique','Mozambique'),
    ('Myanmar','Myanmar'),
    ('Namibia','Namibia'),
    ('Nauru','Nauru'),
    ('Nepal','Nepal'),
    ('Netherlands (the)','Netherlands (the)'),
    ('New Zealand','New Zealand'),
    ('Nicaragua','Nicaragua'),
    ('Niger (the)','Niger (the)'),
    ('Nigeria','Nigeria'),
    ('North Macedonia','North Macedonia'),
    ('Norway','Norway'),
    ('Oman','Oman'),
    ('Pakistan','Pakistan'),
    ('Palau','Palau'),
    ('Panama','Panama'),
    ('Papua New Guinea','Papua New Guinea'),
    ('Paraguay','Paraguay'),
    ('Peru','Peru'),
    ('Philippines (the)','Philippines (the)'),
    ('Poland','Poland'),
    ('Portugal','Portugal'),
    ('Qatar','Qatar'),
    ('Republic of Korea (the)','Republic of Korea (the)'),
    ('Republic of Moldova (the)','Republic of Moldova (the)'),
    ('Romania','Romania'),
    ('Russian Federation (the)','Russian Federation (the)'),
    ('Rwanda','Rwanda'),
    ('Saint Kitts and Nevis','Saint Kitts and Nevis'),
    ('Saint Lucia','Saint Lucia'),
    ('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines'),
    ('Samoa','Samoa'),
    ('San Marino','San Marino'),
    ('Sao Tome and Principe','Sao Tome and Principe'),
    ('Saudi Arabia','Saudi Arabia'),
    ('Senegal','Senegal'),
    ('Serbia','Serbia'),
    ('Seychelles','Seychelles'),
    ('Sierra Leone','Sierra Leone'),
    ('Singapore','Singapore'),
    ('Slovakia','Slovakia'),
    ('Slovenia','Slovenia'),
    ('Solomon Islands','Solomon Islands'),
    ('Somalia','Somalia'),
    ('South Africa','South Africa'),
    ('South Sudan','South Sudan'),
    ('Spain','Spain'),
    ('Sri Lanka','Sri Lanka'),
    ('Sudan (the)','Sudan (the)'),
    ('Suriname','Suriname'),
    ('Sweden','Sweden'),
    ('Switzerland','Switzerland'),
    ('Syrian Arab Republic (the)','Syrian Arab Republic (the)'),
    ('Tajikistan','Tajikistan'),
    ('Thailand','Thailand'),
    ('Timor-Leste','Timor-Leste'),
    ('Togo','Togo'),
    ('Tonga','Tonga'),
    ('Trinidad and Tobago','Trinidad and Tobago'),
    ('Tunisia','Tunisia'),
    ('Turkey','Turkey'),
    ('Turkmenistan','Turkmenistan'),
    ('Tuvalu','Tuvalu'),
    ('Uganda','Uganda'),
    ('Ukraine','Ukraine'),
    ('United Arab Emirates (the)','United Arab Emirates (the)'),
    ('United Kingdom of Great Britain and Northern Ireland (the)','United Kingdom of Great Britain and Northern Ireland (the)'),
    ('United Republic of Tanzania (the)','United Republic of Tanzania (the)'),
    ('United States of America (the)','United States of America (the)'),
    ('Uruguay','Uruguay'),
    ('Uzbekistan','Uzbekistan'),
    ('Vanuatu','Vanuatu'),
    ('Venezuela (Bolivarian Republic of)','Venezuela (Bolivarian Republic of)'),
    ('Viet Nam','Viet Nam'),
    ('Yemen','Yemen'),
    ('Zambia','Zambia'),
    ('Zimbabwe','Zimbabwe'),
    ('Holy See (the) *','Holy See (the) *'),
    ('State of Palestine (the) *','State of Palestine (the) *'),
    ('Cook Islands (the) **','Cook Islands (the) **'),
    ('Niue **','Niue **'),
]
