# Generated by Django 4.0.3 on 2022-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=250)),
                ('picture', models.ImageField(default='https://www.pinclipart.com/picdir/middle/555-5554182_travel-globe-clipart-png-download.png', upload_to='main_app/static/images')),
            ],
        ),
    ]
