# Generated by Django 4.0.3 on 2022-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='picture_url',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
