# Generated by Django 4.0.3 on 2022-03-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='highlights',
            field=models.ManyToManyField(to='main_app.highlight'),
        ),
    ]
