# Generated by Django 4.0.3 on 2022-03-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_picture_destination_picture_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture_upload',
            field=models.ImageField(default=None, upload_to='main_app/static/images'),
        ),
    ]
