# Generated by Django 4.0.3 on 2022-04-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review_remove_country_comment_remove_country_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.CharField(blank=True, default='https://mir-s3-cdn-cf.behance.net/projects/max_808/8dd5b929789141.Y3JvcCw1MzIsNDE2LDAsMA.png', max_length=100, null=True),
        ),
    ]
