# Generated by Django 4.0.3 on 2022-03-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_destination_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture_upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/static/images'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='picture_url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
