# Generated by Django 4.0.3 on 2022-03-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_destination_picture_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture_url',
            field=models.CharField(blank=True, default='https://esquilo.io/png/thumb/0X9uoIGOFesUvGf-Travel-Globe-PNG-Free-Download.png', max_length=100, null=True),
        ),
    ]
