# Generated by Django 4.0.3 on 2022-03-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_destination_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture_url',
            field=models.CharField(blank=True, default='https://www.pngitem.com/pimgs/m/775-7750535_travel-globe-png-free-download-transparent-png.png', max_length=100, null=True),
        ),
    ]
