# Generated by Django 4.0.3 on 2022-03-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_name_location_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date_visited']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='date',
            new_name='date_visited',
        ),
    ]
